### ISSUE TITLE
installation: include flask-shell-ipython?

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-base#115]
`flask-shell-ipython` is a flask module that changes the default python shell to IPython when running the command `flask shell` (or `invenio shell` in our case)

**Comment by remileduc** [comment]
Fixed in https://github.com/inveniosoftware/invenio-base/pull/116

**Comment by remileduc** [comment]
updated

**Comment by egabancho** [comment]
Just a small note, we have added it only to the developer requirements https://github.com/CERNDocumentServer/cds/blob/cdslabs_qa/requirements.developer.txt#L30, I don't know if it makes sense to have it everywhere (I have nothing against it though)

**Comment by remileduc** [comment]
I asked during this morning meeting and people wanted it for production too because it is more convenient...
