### ISSUE TITLE
docs: document instance entrypoints/migrate-secret-key cli commands

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-base#126]
The two CLI commands below are not documented:

```
inveniomanage instance entrypoints
inveniomanage instance migrate-secret-key
```

Especially secret key migration would need docs - i.e. how should other modules hook into the secret key migration.

Check also API documentation for missing modules.

**Comment by dinosk** [comment]
Presentation from the invenio developer's forum about this feature: https://docs.google.com/presentation/d/1Mpkt5XtZO7f5ygUkXQWl-iC1xdtcHlym9qpreVQFtMM/edit
