### ISSUE TITLE
`before_(app_)first_request` deprecation and removal in Flask v2.3

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-base#171]
In [Flask v2.2](https://flask.palletsprojects.com/en/2.2.x/changes/#version-2-2-0) `before_(app_)first_request` was deprecated and will be removed in v2.3.

We are currently using this through various modules for registering menus or other special cases:

- [`before_first_request`](https://github.com/search?q=org%3Ainveniosoftware+before_first_request&type=code)
- [`before_app_first_request`](https://github.com/search?q=org%3Ainveniosoftware+before_app_first_request&type=code)
- (Optional, but similar) [`Blueprint.record_once`](https://github.com/search?q=org%3Ainveniosoftware%20record_once&type=code) (see https://github.com/inveniosoftware/invenio-base/issues/171#issuecomment-1498764670 👇 )

We should either:

- Pin `Flask < 2.3` in this module
- Refactor the code not to use these decorators. This is pretty difficult since the proposed alternative is to "Run setup code when creating the application instead."... This means we have to hook in the `invenio-app` lifecycle to introduce a similar mechanism.

**Comment by jrcastro2** [comment]
11 repositories affected by this.

- [flask-menu](https://github.com/inveniosoftware/flask-menu):
  - [classy.py](https://github.com/inveniosoftware/flask-menu/blob/54a48102a5189cc87af37de610779a96cc294118/flask_menu/classy.py#L34)
  - [\_\_init__.py](https://github.com/inveniosoftware/flask-menu/blob/54a48102a5189cc87af37de610779a96cc294118/flask_menu/__init__.py#L361)
- [invenio-administration](https://github.com/inveniosoftware/invenio-administration)
  - [ext.py](https://github.com/inveniosoftware/invenio-administration/blob/2bf3b9dc7a06c3dc6fa79e7043a3aa7292040d2d/invenio_administration/ext.py#L89)
  - [admin.py](https://github.com/inveniosoftware/invenio-administration/blob/e24ca2e853528ef2873da12e8f12322f72a0323f/invenio_administration/admin.py#L65)
- [invenio-github](https://github.com/inveniosoftware/invenio-github):
  - [ext.py](https://github.com/inveniosoftware/invenio-github/blob/7d3678c81e8d4f8f60023f0832d6166998c53412/invenio_github/ext.py#L77)
- [invenio-records-rest](https://github.com/inveniosoftware/invenio-records-rest)
  - [test_custom_endpoints.py](https://github.com/inveniosoftware/invenio-records-rest/blob/d05d717ee53a9aaa835d1ef2bee74b21c04db713/tests/test_custom_endpoints.py#L38)
- [invenio-deposit](https://github.com/inveniosoftware/invenio-deposit)
  - [ext.py](https://github.com/inveniosoftware/invenio-deposit/blob/f6371bdf95260c3cb10c986f8ac5a42ec0c328ab/invenio_deposit/ext.py#L122)  
- [invenio-admin](https://github.com/inveniosoftware/invenio-admin)
  - [ext.py](https://github.com/inveniosoftware/invenio-admin/blob/085aaaad3f4ed5ab4d68674905953dd3c1225930/invenio_admin/ext.py#L141)
  - [test_invenio_admin.py](https://github.com/inveniosoftware/invenio-admin/blob/085aaaad3f4ed5ab4d68674905953dd3c1225930/tests/test_invenio_admin.py#L78)
  - [views.py](https://github.com/inveniosoftware/invenio-admin/blob/085aaaad3f4ed5ab4d68674905953dd3c1225930/invenio_admin/views.py#L37)
- [invenio-oauthclient](https://github.com/inveniosoftware/invenio-oauthclient)
  - [ext.py](https://github.com/inveniosoftware/invenio-oauthclient/blob/71d25b6288f8105fa4a19b1e15f965a4d1ec2738/invenio_oauthclient/ext.py#L165)
- [invenio-oauth2server](https://github.com/inveniosoftware/invenio-oauth2server)
  - [consumer.py](https://github.com/inveniosoftware/invenio-oauth2server/blob/17127b948cb3e65ee49db10925c261a1f1936956/examples/consumer.py#L198)
- [invenio-accounts](https://github.com/inveniosoftware/invenio-accounts)
  - [settings.py](https://github.com/inveniosoftware/invenio-accounts/blob/d97e34cbff43a535bdfe79e5123f15d83ecd65e1/invenio_accounts/views/settings.py#L48)
- [invenio-app-rdm](https://github.com/inveniosoftware/invenio-app-rdm)
  - [views.py](https://github.com/inveniosoftware/invenio-app-rdm/blob/cb5bd39104c8a40ef98a18b3b7c42d7da877e08d/invenio_app_rdm/theme/views.py#L36)
  - [ui.py](https://github.com/inveniosoftware/invenio-app-rdm/blob/76518def21a56b44b04000516c6e64ed7b2974d1/invenio_app_rdm/users_ui/views/ui.py#L67)
  - [communities_ui/views/ui.py ](https://github.com/inveniosoftware/invenio-app-rdm/blob/76518def21a56b44b04000516c6e64ed7b2974d1/invenio_app_rdm/users_ui/views/ui.py#L67)
- [invenio-communities](https://github.com/inveniosoftware/invenio-communities)
  - [ui.py](https://github.com/inveniosoftware/invenio-communities/blob/5f46f455ccac721489b33e88b2877d07ae85feaa/invenio_communities/views/ui.py#L102)

Some usefull resources:
- Discussion about `before_first_request` with some potential solutions: https://github.com/pallets/flask/discussions/4711

**Comment by utnapischtim** [comment]
NOTES:
- would that solution also makes `@blueprint.record_once` decorators obsolete?

**Comment by utnapischtim** [comment]
> > * would that solution also makes `@blueprint.record_once` decorators obsolete?
> 
> I would say yes (at least from a [quick search](https://github.com/search?q=org%3Ainveniosoftware%20record_once&type=code)). The main difference with the `before_(app_)first_request` usage, is that it doesn't depend on an application context being pushed, but has access to the `app` via `state.app`. It still assumes that all extensions have been initialized though.
> 
> I think whenever we're using a `current_XYZ` in these function, we're assuming app context, but it's not necessary actually... If you have the `app` object, you can usually access any of these `current_XYZ` objects via `app.extensions['<XYZ-module>'].XYZ`.

Good to know. thank you. 

Should i include those examples in the affected list?

Is the proposed method to fix that DeprecationWarning still under discussion or can i go further and apply it?

**Comment by slint** [comment]
> Should i include those examples in the affected list?

Yes, I think they're good candidates for this type of logic.

> Is the proposed method to fix that DeprecationWarning still under discussion or can i go further and apply it?

https://github.com/inveniosoftware/invenio-base/pull/172 and https://github.com/inveniosoftware/invenio-app/pull/88 are the "leading" implementations. Personally, I'm still a bit hesitant about the naming (I like more [the `finalize_init_app` naming proposed in flask](https://github.com/pallets/flask/discussions/4711#discussioncomment-3269883)), but otherwise, I think that's the direction we're going with.

An alternative to adding yet another entrypoint, would be to move the logic in the extensions and introduce an optional `finalize_init_app()` method, which when exists gets called for all the extensions defined in the original `inenio_app.apps` and `invenio_app.api_apps`.

**Comment by utnapischtim** [comment]
@slint
i need some advice/decision for flask-menu.

#i-would-like-to-refactore
The package was not refactored for a long time. I would like to apply the common invenio structure with the ext.py  and proxies.py files. Migrate to setup.cfg and black. Further, as i researched, the `classy.py` file is not used within `inveniosoftware`, should we keep it or could we remove it? 

#if-we-not-refactore-and-remove-classy
how do we proceed with with the `before_first_request` decorator in classy.py? In my opinion it is not worth the time to keep that functionality. We could release a new major version which indicates that the classy.py has been removed.

#structural-problem
there is a problem with the `register_menu` decorator. This decorator uses the `before_first_request` decorator and the `register_menu` decorator is used in 4-5 inveniosoftware packages. In my opinion the `register_menu` decorator should be removed and the usage of the decorator has to be refactored to use the newly introduced `finalize_app_entry_points`

**Comment by slint** [comment]
#i-would-like-to-refactore The package was not refactored for a long time. I would like to apply the common invenio structure with the ext.py and proxies.py files. Migrate to setup.cfg and black. Further, as i researched, the `classy.py` file is not used within `inveniosoftware`, should we keep it or could we remove it?

+1 for updating the structure and modernizing. What we have to keep in mind is that this is `Flask-*` package and not `invenio-*`, so we have to assume that there might be users in the wild. The best would be in any case to release a major bump with breaking changes if that's easier.

> #if-we-not-refactore-and-remove-classy how do we proceed with with the `before_first_request` decorator in classy.py? In my opinion it is not worth the time to keep that functionality. We could release a new major version which indicates that the classy.py has been removed.

We can remove `classy.py` and support for Flask-Classy, and make a major version bump.

> #rename-entrypoint i would like to rename it to `finalize_app_entry_points` and then the entrypoint: `invenio_base.finalize_app`. in my eyes it describes the best what it should do. what do you think?

I have a feeling that entrypoints are a bit "esoteric" at this point to how we do things in Invenio... Would it make sense to explore more towards what the discussion in Flask also suggested, i.e. a `finalize_init_app` method as part of the extensions "interface/convention"? We could then just call that method (if it exists) for each extension in the existing `inenio_app.apps` and `invenio_app.api_apps` entrypoints.

> #structural-problem there is a problem with the `register_menu` decorator. This decorator uses the `before_first_request` decorator and the `register_menu` decorator is used in 4-5 inveniosoftware packages. In my opinion the `register_menu` decorator should be removed and the usage of the decorator has to be refactored to use the newly introduced `finalize_app_entry_points`. My point is, if we keep the `register_menu` decorator we would have to find a solution where the decorator could still be used, but what the decorator does is done on initializing the app, which seems not possible in my eyes.

This is a bigger problem in the way we integrate `Flask-*` modules in general in Invenio, since we usually initialize the extensions inside our own `InvenioXYZ` extensions, and thus deny using the common pattern of accessing methods of an un-initialized extension. See [Flask-Talisman as an example](https://github.com/inveniosoftware/invenio-app/issues/22), which is technically unusable in its advertised decorator-style usage.

I think we should/could solve this problem as well as part of this refactoring here.

> SIDENOTE: the `register_breadcrumb` from `flask-breadcrumps` is a `register_menu` wrapper, which means, this has also to be refactored (in the sense of removed)
> This change would affect code like in [invenio-accounts](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/views/security.py#L28-L40)

Yes, these two modules are very tightly coupled, and as an extension any module that adds to the user setting pages. I think before releasing any breaking changes we should first pin the dependency [in `invenio-theme`](https://github.com/inveniosoftware/invenio-theme/blob/7893ec0cac832fbde16ee85881d0f16feccfadf3/setup.cfg#L30-L31) (this is the first place where it's introduced, so thus a "coordinator module").
 
> SIDENOTE: is [this](https://github.com/inveniosoftware/invenio-administration/blob/44510475b813ce00f37cd75472a0a200e9b17240/invenio_administration/ext.py#L89) in invenio-administration the example that it is not possible to replace all `before_*_request` decorators with the entrypoint method?

This one looks replaceable actually, but depends on some "local" variables (i.e. `view_class`), so it might be a bit tricky.

**Comment by utnapischtim** [comment]
#about-flask-menu
flask-menu depends on flask-classy which is last updated 2014 and superseded by flask-classful (last update 12.2021). flask-classful is not compatible with werkzeug >2.3.0. keeping the classy.py would increase the amount of time to refactore the whole code and make it compatible with werkzeug >=2.3.0 and flask >=2.3.0

the rest tomorrow

**Comment by utnapischtim** [comment]
@slint do we still support invenio-admin on v12

**Comment by utnapischtim** [comment]
### overview of open PR's all draft. this are for now only the changes of before(_app)_first_request
- https://github.com/inveniosoftware/invenio-base/pull/172
- https://github.com/inveniosoftware/invenio-app/pull/88
- https://github.com/inveniosoftware/invenio-administration/pull/171
- https://github.com/inveniosoftware/invenio-accounts/pull/440
- https://github.com/inveniosoftware/invenio-app-rdm/pull/2218
- https://github.com/inveniosoftware/invenio-oauthclient/pull/303
- https://github.com/inveniosoftware/invenio-oauth2server/pull/248

### next step is to see how to find a solution with the register_menu decorator

**Comment by ntarocco** [comment]
> @slint do we still support `invenio-admin` and `invenio-deposit`. as i know `invenio-admin` is deprecated in favor of `invenio-administration` and `invenio-deposit` had the last release 2019. i saw that `invenio-deposit` is a dependency of `invenio-github`.

Correct: no more support to `invenio-admin` and `invenio-deposit`.
About `invenio-github`, I suspect it will be refactored soon (current or next sprint) to enable GitHub integration in the new ZenodoRDM. `invenio-deposit` will disappear.

If it is easy to fix `invenio-admin`, I would fix it anyway because we have other running services that still use `invenio-admin` :)

**Comment by utnapischtim** [comment]
@slint 
how should we do with `flask-security-invenio`? as the name indicates it is a flask package, but if i add an entrypoint to `invenio_base` it is not more independent to `invenio-*` packages.
