### ISSUE TITLE
app: instance and static folder paths

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-base#33]
The current locations of instance and folder paths doesn't work nicely when used through ``python manage.py``.

**Comment by nharraud** [comment]
There doesn't seem to be any way to disable the `/static` endpoint generated for each application in `invenio_base.app:base_app`. When `static_folder` is set to None (default value), it generates a path to the instance directory.
This creates an `/api/static` endpoint.

**Comment by jirikuncar** [comment]
as long as it returns 404 it's fine :wink:

**Comment by jirikuncar** [comment]
> The current locations of instance and folder paths doesn't work nicely when used through `python manage.py`.

@lnielsen Can we agree on recommendation to **always** install `invenio/overlay`?

**Comment by nharraud** [comment]
@jirikuncar I moved the comment to its own issue #36

**Comment by lnielsen** [comment]
> @lnielsen Can we agree on recommendation to always install invenio/overlay?

Yes I think so - still issues to sort out, such as being able to specify the app template folder (which overwrite every possible template in blueprints).

**Comment by jirikuncar** [comment]
I would generate `setup.py` instead of `manage.py` and then one is ready for "production".

**Comment by lnielsen** [comment]
I'm closing this issue as it's now fully customisable from the instance where the instance and static folder should be located.
