### ISSUE TITLE
app: disable /static endpoint

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-base#36]
There doesn't seem to be any way to disable the `/static` endpoint generated for each application in `invenio_base.app:base_app`. When static_folder is set to None (default value), it generates a path to the instance directory.
This creates an `/api/static` endpoint.

**Comment by lnielsen** [comment]
Confirmed.

Due to https://github.com/inveniosoftware/invenio-base/blob/next/invenio_base/app.py#L213-L215 + 
https://github.com/mitsuhiko/flask/blob/master/flask/app.py#L538-L541

**Comment by lnielsen** [comment]
Related to #33
