### ISSUE TITLE
tests: quantified code fixes

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-base#41]
https://www.quantifiedcode.com/app/project/gh:inveniosoftware:invenio-base/diff/26fd70fb4f34cb1446ba56e08a33628961bd68ea/7dac34bf68a3bd434e8bd75a59cfb7cd716b7b5c/issues?groups=code_patterns%3A1sMHNVxe%3Af0,code_patterns%3A539Wia7V%3Af0,code_patterns%3A4ACGxFj1

**Comment by programmdesign** [comment]
Hi @lnielsen, quite an interesting issue ;-) Let me know if I can help or if I can answer any questions. :-)
