### ISSUE TITLE
api: clean argument names

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-base#42]
Improve naming convention of `ext_entry_points` and `bp_entry_points` (see https://github.com/inveniosoftware/invenio-base/blob/master/invenio_base/app.py#L42-L43)

- [ ] rename arguments
- [ ] update cookiecutter templates

--
cc @lnielsen

**Comment by lnielsen** [comment]
This is a duplicate of #32 so I'll close it.
