### ISSUE TITLE
installation: entry_points for CLI

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-base#81]
Do we want to use entry_points to load Flask commands? If yes, shall we use entry_points group [`flask.commands`](http://flask.pocoo.org/docs/0.11/cli/#cli-plugins) or create new configuration option for the entry_point group name in `create_cli` factory?

--
cc @inveniosoftware/triagers

**Comment by tiborsimko** [comment]
Hmm, the entry points and `flask.commands` would make sense.

**Comment by jirikuncar** [comment]
Good. There haven't been any objections for two weeks, hence we are going to recommend using `flask.commands` to load CLI commands.

--
addresses inveniosoftware/invenio#3657
cc @inveniosoftware/triagers
